version: "3.4"

services:

  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    #    networks:
    #      renameThisNetwork:
    #        ipv4_address: 172.42.1.2
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  app_node:
    container_name: app_node
    restart: always
    #    networks:
    #      renameThisNetwork:
    #        ipv4_address: 172.42.1.20
    build:
      context: .
      target: app_node
    volumes:
      - .:/srv:rw

  app:
    container_name: app
    restart: always
    #    networks:
    #      renameThisNetwork:
    #        ipv4_address: 172.42.1.21
    build:
      context: .
      target: app
    volumes:
      - .:/srv:rw
    depends_on:
      - mysql
    ports:
      - 8000:80
    environment:
      DATABASE_URL: mysql://root:secret@mysql:3306/app
      APP_ENV: dev

#networks:
#  renameThisNetwork:
#    ipam:
#      driver: default
#      config:
#        - subnet: "172.42.0.0/16"
